package com.example.josuerey.helloworld;

import android.app.ProgressDialog;
import android.content.ContentValues;
import android.content.Intent;
import android.provider.Settings;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.EditText;
import android.widget.Toast;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.JsonRequest;
import com.android.volley.toolbox.Volley;
import com.example.josuerey.helloworld.domain.metadata.Metadata;
import com.example.josuerey.helloworld.domain.metadata.MetadataRepository;
import com.example.josuerey.helloworld.network.APIClient;
import com.example.josuerey.helloworld.utilidades.Utilidades;

import org.json.JSONException;
import org.json.JSONObject;

public class MainActivity extends AppCompatActivity {

    public final static String METADATA_ID_PROPERTY = "metadataId";
    public final static String METADATA_PROPERTY = "metadata";
    private EditText campoNom_Ruta;
    private EditText campoVia;
    private EditText campoNum_Econ;
    private EditText campoEncuestador;
    private MetadataRepository metadataRepository;
    private int metadataId;
    private final static String TAG = "MainActivity";
    private APIClient apiClient;
    private String android_device_id;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        android_device_id = Settings.Secure.getString(this.getContentResolver(),
                Settings.Secure.ANDROID_ID);

        Log.i(TAG, "Unique id: " + android_device_id);

        campoNom_Ruta=(EditText) findViewById(R.id.editTextRuta);
        campoVia=(EditText) findViewById(R.id.editTextVia);
        campoNum_Econ=(EditText) findViewById(R.id.editTextNumEcon);
        campoEncuestador=(EditText) findViewById(R.id.editTextEnc);

        metadataRepository = new MetadataRepository(getApplication());
        apiClient = new APIClient(getApplication());
    }

    public void onClick(View view){

        Intent miIntent=null;
        switch (view.getId()){

            case R.id.btnConsultaRecorrido:
                miIntent=new Intent(MainActivity.this,ConsultarRecorridos.class);
                break;

            case R.id.btnConsultaLista:
                miIntent=new Intent(MainActivity.this,ConsultarRecorridosLista.class);
                break;
            case R.id.btnStart:
                try{
                    getAuthorization();
                } catch (JSONException e) {
                    e.printStackTrace();
                }
                break;
        }
        if (miIntent!=null){
            startActivity(miIntent);
        }
    }

    /**
     *
     * @return id autogenerated for the persisted row.
     */
    private Metadata saveMetadata(){

        Metadata metadata = Metadata.builder()
                .capturist(campoEncuestador.getText().toString())
                .economicNumber(campoNum_Econ.getText().toString())
                .via(campoVia.getText().toString())
                .deviceId(android_device_id)
                .route(campoNom_Ruta.getText().toString()).build();

        metadataId = (int) metadataRepository.insert(metadata);
        metadata.setId(metadataId);
        return metadata;
    }

    public void registrarRecorridos(){

        ContentValues values=new ContentValues();
        values.put(Utilidades.CAMPO_NOM_RUTA,campoNom_Ruta.getText().toString());
        values.put(Utilidades.CAMPO_VIA,campoVia.getText().toString());
        values.put(Utilidades.CAMPO_NUM_ECON,campoNum_Econ.getText().toString());
        values.put(Utilidades.CAMPO_ENCUESTADOR,campoEncuestador.getText().toString());

    }


    private void getAuthorization() throws JSONException {

        RequestQueue queue = Volley.newRequestQueue(this);
        String userToken= "1234";
        String url ="http://u856955919.hostingerapp.com/api/user?api_token="+userToken;
        final ProgressDialog pdLoading = new ProgressDialog(this);
        pdLoading.setMessage("\tLoading...");
        pdLoading.show();

        // Request a string response from the provided URL.
        JsonRequest<JSONObject> stringRequest = new JsonObjectRequest(Request.Method.GET, url,
                null,new Response.Listener<JSONObject >() {
            @Override
            public void onResponse(JSONObject  response) {
                // Display the first 500 characters of the response string.
                Log.i(TAG, response.toString());
                try {

                    evalResponse(response);
                } catch (JSONException e) {

                    e.printStackTrace();
                }
                pdLoading.dismiss();
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                Log.i(TAG, "Did not worked");
                pdLoading.dismiss();
            }
        });

        // Add the request to the RequestQueue.
        queue.add(stringRequest);
    }

    private void evalResponse(JSONObject response) throws JSONException {
        String msg;
        if (response != null) {
            String isActive = response.getString("activo");

                if (isActive.equals("1")) {
                    Metadata metadata = saveMetadata();
                    Log.i(TAG, metadata.toString());
                    apiClient.postMetadata(metadata);

                    msg = "Bienvenido " + campoEncuestador.getText().toString();
                    Intent myIntent = new Intent(MainActivity.this, TrackerActivity.class);
                    myIntent.putExtra(METADATA_ID_PROPERTY, String.valueOf(metadataId));
                    myIntent.putExtra(METADATA_PROPERTY, metadata.toString());
                    myIntent.putExtra("Route", metadata.getRoute());
                    myIntent.putExtra("econNumber", metadata.getEconomicNumber());
                    MainActivity.this.startActivity(myIntent);
                    finish();

                } else
                    msg = "You are not allowed to use this app anymore, until you pay.";

            } else {
                msg = "Unable to connect to remote server.";
            }

        Log.i(TAG, "Auth:" + msg);
        Toast.makeText(MainActivity.this, msg,
                Toast.LENGTH_SHORT).show();
    }
}
