package com.sgcities.tdc.optimizer.preloaddata;

import android.support.annotation.NonNull;

import com.sgcities.tdc.optimizer.domain.routeviarelationship.RouteViaRelationship;

public class RouteViaRelationshipData {

    @NonNull
    public static RouteViaRelationship[] getRouteViaRelationshipData() {
        return new RouteViaRelationship[] {
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(1).build(),
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(2).build(),
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(3).build(),
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(4).build(),
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(5).build(),
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(6).build(),
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(7).build(),
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(85).build(),
                RouteViaRelationship.builder().viaOfStudyId(1).routeId(8).build(),

                RouteViaRelationship.builder().viaOfStudyId(2).routeId(9).build(),
                RouteViaRelationship.builder().viaOfStudyId(2).routeId(10).build(),
                RouteViaRelationship.builder().viaOfStudyId(2).routeId(11).build(),
                RouteViaRelationship.builder().viaOfStudyId(2).routeId(12).build(),
                RouteViaRelationship.builder().viaOfStudyId(2).routeId(13).build(),
                RouteViaRelationship.builder().viaOfStudyId(2).routeId(14).build(),

                RouteViaRelationship.builder().viaOfStudyId(3).routeId(15).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(9).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(16).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(17).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(18).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(19).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(20).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(21).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(10).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(11).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(22).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(23).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(24).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(25).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(26).build(),
                RouteViaRelationship.builder().viaOfStudyId(3).routeId(27).build(),

                RouteViaRelationship.builder().viaOfStudyId(4).routeId(28).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(29).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(30).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(31).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(86).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(32).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(33).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(34).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(35).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(36).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(37).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(38).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(39).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(40).build(),
                RouteViaRelationship.builder().viaOfStudyId(4).routeId(41).build(),

                RouteViaRelationship.builder().viaOfStudyId(5).routeId(42).build(),
                RouteViaRelationship.builder().viaOfStudyId(5).routeId(43).build(),
                RouteViaRelationship.builder().viaOfStudyId(5).routeId(44).build(),
                RouteViaRelationship.builder().viaOfStudyId(5).routeId(45).build(),
                RouteViaRelationship.builder().viaOfStudyId(5).routeId(46).build(),
                RouteViaRelationship.builder().viaOfStudyId(5).routeId(47).build(),
                RouteViaRelationship.builder().viaOfStudyId(5).routeId(48).build(),
                RouteViaRelationship.builder().viaOfStudyId(5).routeId(49).build(),

                RouteViaRelationship.builder().viaOfStudyId(6).routeId(50).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(51).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(52).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(1).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(53).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(54).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(55).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(56).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(57).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(58).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(4).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(16).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(17).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(59).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(60).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(61).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(62).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(63).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(18).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(64).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(5).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(6).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(65).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(66).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(67).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(68).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(87).build(),
                RouteViaRelationship.builder().viaOfStudyId(6).routeId(88).build(),

                RouteViaRelationship.builder().viaOfStudyId(7).routeId(69).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(70).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(71).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(72).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(43).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(44).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(45).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(46).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(47).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(73).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(74).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(64).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(75).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(19).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(20).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(76).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(21).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(77).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(78).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(22).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(23).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(24).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(79).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(25).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(80).build(),
                RouteViaRelationship.builder().viaOfStudyId(7).routeId(49).build(),

                RouteViaRelationship.builder().viaOfStudyId(8).routeId(15).build(),
                RouteViaRelationship.builder().viaOfStudyId(8).routeId(70).build(),
                RouteViaRelationship.builder().viaOfStudyId(8).routeId(58).build(),
                RouteViaRelationship.builder().viaOfStudyId(8).routeId(16).build(),
                RouteViaRelationship.builder().viaOfStudyId(8).routeId(17).build(),
                RouteViaRelationship.builder().viaOfStudyId(8).routeId(18).build(),
                RouteViaRelationship.builder().viaOfStudyId(8).routeId(64).build(),
                RouteViaRelationship.builder().viaOfStudyId(8).routeId(81).build(),
                RouteViaRelationship.builder().viaOfStudyId(9).routeId(82).build(),
                RouteViaRelationship.builder().viaOfStudyId(9).routeId(83).build(),
                RouteViaRelationship.builder().viaOfStudyId(9).routeId(74).build(),
                RouteViaRelationship.builder().viaOfStudyId(9).routeId(75).build(),
                RouteViaRelationship.builder().viaOfStudyId(9).routeId(76).build(),
                RouteViaRelationship.builder().viaOfStudyId(9).routeId(89).build(),
                RouteViaRelationship.builder().viaOfStudyId(9).routeId(90).build(),
                RouteViaRelationship.builder().viaOfStudyId(9).routeId(11).build(),

                RouteViaRelationship.builder().viaOfStudyId(10).routeId(69).build(),
                RouteViaRelationship.builder().viaOfStudyId(10).routeId(72).build(),
                RouteViaRelationship.builder().viaOfStudyId(10).routeId(84).build()
        };
    }
}
